default_config:

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: metric
  time_zone: Europe/Berlin

http:
  base_url: !secret base_url
  
lovelace:
  mode: yaml

group: !include_dir_named group
light: !include_dir_merge_list light

shell_command:
  pull_config: cd /config && git pull -f

# https://www.home-assistant.io/integrations/tado/
tado:
  username: !secret tado_username
  password: !secret tado_password

