homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named customizations/entities
  customize_domain: !include_dir_merge_named customizations/domains
  customize_glob: !include_dir_merge_named customizations/globs

default_config:

# https://www.home-assistant.io/integrations/tado/
tado:
  username: !secret tado_username
  password: !secret tado_password