default_config:

homeassistant:
  packages: !include_dir_named packages

http:
  base_url: !secret base_url

lovelace:
  mode: yaml

group: !include_dir_named group
light: !include_dir_merge_list light
scene: !include_dir_merge_list scene
automation: !include_dir_merge_list automation

shell_command:
  pull_config: cd /config && git pull -f

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  discovery: true
  certificate: /tls/ca.crt
  client_key: /tls/tls.key
  client_cert: /tls/tls.crt

# google_assistant: 
#   project_id: !secret google_assistant_project_id
#   service_account:
#     client_email: !secret google_assistant_service_account_email
#     private_key: !secret google_assistant_service_account_key

#   report_state: true

#   expose_by_default: false
#   entity_config: !include_dir_merge_named google_assistant_entities

# octoprint:
#   host: !secret octoprint_host
#   port: 5000
#   api_key: !secret octoprint_apikey
#   name: CR10S-Pro
#   bed: true
#   number_of_tools: 1

# remote:
#   - platform: harmony
#     name: Harmony Hub
#     host: harmonyhub

# webostv:
#   name: Living Room TV
#   host: lgwebostv