- platform: group
  name: Bedroom Ceiling
  entities:
    - light.hue_ctl_2

- platform: group
  name: Bedroom Bedside
  entities:
    - light.hue_ctl_1

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_ceiling
    - light.bedroom_bedside
