- platform: group
  name: Living Room Ceiling
  entities: []

- platform: group
  name: Living Room TV Backlight
  entities: []

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_ceiling
    - light.living_room_tv_backlight
