- alias: Turn on bathroom lights when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.bathroom_lights
    data:
      brightness: 255

- alias: Turn off bathroom light when no motion is detected for 10 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    to: "off"
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.bathroom_lights