- alias: Turn on kitchen lights when motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_occupancy
    to: "on"
  action:
    service: light.turn_on
    entity_id: light.kitchen_lights
    data:
      brightness: 255

- alias: Turn off kitchen lights when no motion is detected for 10 minutes
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_occupancy
    to: "off"
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights