- alias: Active "Watch Movie" scene when Harmony Hub is on
  trigger:
    platform: state
    entity_id: remote.harmony_hub
    to: "on"
  action:
    service: scene.turn_on
    entity_id: scene.watch_movie